env = ""
email_account = "verify@keysafe.network"
email_password = ""
email_server = ""
db_user = ""
db_password = ""
db_port = 3306
db_name = "keysafe"
node_api_port = 30000
secret = "keysafe_password_for_test"
cru_api_server = ""